<div class="halaman">
	<h2>Bawa Aspirasi, 850 Perangkat Desa Bertolak ke Jakarta</h2>
	<p>Sebanyak 850 perangkat desa dari Kabupaten Wonosobo yang tergabung dalam Persatuan Perangkat Desa Indonesia (PPDI) Kabupaten Wonosobo bertolak menuju Jakarta, Selasa (24\/1\/2022)&nbsp; guna mengikuti Silaturahmi&nbsp;Nasional PPDI Jilid III di Jakarta.</p>
	<p>Rombongan yang merupakan perwakilan dari 263 desa di Wonosobo tersebut berangkat menggunakan 17 bus untuk bergabung dengan perangkat desa dari seluruh Indonesia guna menyampaikan aspirasinya.</p>
	<p>Ketua PPDI kabupaten Wonosobo Darjin Traju Visa menjelaskan, keberangkatan hampir seperempat dari perangkat desa di Wonosobo&nbsp; tersebut membawa aspirasi seluruh perangkat yang ada, dengan&nbsp;beberapa tuntutan antara lain, menolak gagasan beberapa pihak yang menghendaki periodesasi perangkat desa sama dengan kepala desa, juga menolak wacana status kepegawaian perangkat desa menjadi PNS atau P3K.</p>
	<p>Tambah Darjin, utusan perangkat desa dari Wonosobo akan fokus menyuarakan kejelasan status kepegawaian perangkat desa, dengan memperhatikan masa kerja serta memberikan NIAPD. Juga terkait kepastian perlindungan hukum terhadap perangkat desa, yang memberikan rasa aman dan nyaman dalam bekerja, sehingga dapat melaksanakan pembangunan di desa dan pengabdian terhadap masyarakat secara total.</p>
	<p>&rdquo;Nomor Induk Perangkat Desa (NIPD) penting adanya untuk menguatkan kedudukan perangkat desa sebagai bagian dari penyelenggara pemerintahan, terutama dalam tata kelola administrasi pemerintahan desa, masa jabatan perangkat desa tetap maksimal 60 tahun sebagaimana Undang Undang Nomor 6 Tahun 2014 Tentang Desa,&rdquo; jelasnya.</p>
	<p>Jika aspirasi terpenuhi, Darjin memastikan, akan berdampak terhadap kinerja dalam melayani dan mengabdi kepada masyarakat di masing-masing desa. Pasalnya, perangkat akan bekerja dengan lebih aman, nyaman dan total melayani masyarakat 24 jam.</p>
	<p>&ldquo;Kami mendorong penuh&nbsp;Pemerintah&nbsp;Pusat untuk bisa menerbitkan suatu aturan tentang keperangkatan desa yang lebih konkret&nbsp;dan jelas, di undang-undang yang berlaku saat ini baik &nbsp;Perpres maupun&nbsp;Kemendagri belum secara rigid mengatur tentang perangkat desa,&rdquo; tambah Darjin.</p>
	<p>Sementara itu Bupati Wonosobo Afif Nurhidayat kepada media menyampaikan, Silatnas PPID Jilid III diselenggarakan tentu dengan beberapa agenda yang sudah tersusun dan terjadwalkan, harapannya semua terlaksana dengan sukses dan terpenuhi aspirasinya, baik penguatan kelembagaan maupun peningkatan&nbsp; kesejahteraan.</p>
	<p>&ldquo;Kami mendukung penuh ikhtiar PPDI Wonosobo dalam membawa aspirasinya untuk disampaikan dalam forum Silatnas, semoga tercapai apa yang menjadi tujuan dan maksud diadakannya Silatnas,&rdquo; tandasnya</p>
</div>