<div class="halaman">
	<h2>Cetak Atlet Berkelas Nasional dan Internasional, Perguruan Tapak Suci Wonosobo Gelar Kejuaraan Pencak Silat Piala Bupati I</h2>
	<p>cetak-atlet-berkelas-nasional-dan-internasional-perguruan-tapak-suci-wonosobo-gelar-kejuaraan-pencak-silat-piala-bupati-i</p>
	<p>Sebanyak 444 atlet pencak silat Tapak Suci bertanding&nbsp; memperebutkan gelar juara pertama dalam&nbsp; Kejuaraan Piala Bupati I Pencak Silat Tapak Suci Kabupaten Wonosobo, Selasa, (17\/01\/2023), di Sasana Adipira Kencana Wonosobo.
	<p style=\text-align: justify;\>Ketua Pimpinan Daerah (Pimda) Tapak Suci Wonosobo Khanif Rosyadi menyampaikan, selain sebagai&nbsp; ajang kejuaraan, ajang ini juga menjadi media seleksi untuk mempersiapkan 152 atlet unggulan yang akan berkompetisi di ajang POPDA Maret mendatang. Pihaknya mengajak kepada seluruh perguruan tapak suci di Wonosobo untuk bersama mencetak atlet yang mampu menerapkan basis ilmu iman dan akhlak sebagai petarung yang kuat, penuh percaya diri menorehkan prestasi yang gemilang, berkelas nasional maupun internasional.&nbsp;
	<p style=text-align: justify;>&ldquo;Kami melibatkan wasit dari luar perguruan, hal ini penting guna memajukan persilatan di Wonosobo yang lebih sportif,&rdquo; tambahnya.
	<p style=text-align: justify;>Selain itu, Rosyadi menambahkan, Kejuaraan bergengsi itu memperebutkan dua kategori diantaranya, kelas prestasi yang diikuti 152 atlet serta kategori kelas pemasalan atau pemula yang dikuti 292 atlet.&nbsp;
	<p style=text-align: justify;>Senada dengan Rosyadi, Ketua Pimpinan Daerah Muhammadiyah (PDM) Kabupaten Wonosobo Bambang Wen meminta, seluruh atlet dapat bertanding secara sportif dan menjunjung tinggi nilai kejujuran. Tidak sedikit kader tapak suci Wonosobo yang berhasil membawa nama harum daerah di kancah internasional.&nbsp;
	<p style=text-align: justify;>&ldquo;Silat itu seni bela diri, mainkan dengan cantik, kunci terbaik untuk menang adalah iman dan akhlak,&rdquo; ujar Bambang.&nbsp;
	<p style=text-align: justify;>Dijelaskan, peserta terdiri dari 45 cabang latihan se-Wonosobo baik dari amal usaha Muhammadiyah maupun cabang latihan di beberapa ranting aktif persyarikatan Muhammadiyah Wonosobo.<p style=text-align: justify;>Sementara itu, Bupati Wonosobo Afif Nurhidayat dalam sambutannya yang dibacakan Sekretaris Daerah Wonosobo One Andang Wardoyo menegaskan, Pemkab memberikan atensi dan dukungan penuh terhadap kejuaraan tersebut. Dengan harapan mampu mencetak bibit-bibit atlet pencak silat tapak suci Wonosobo yang bereputasi nasional dan internasional.</p>
</div>