<div class="halaman">
	<h2>PPID Pelaksana Wonosobo Diminta Bantu Pertahankan Predikat Keterbukaan Informasi : Informatif</h2>
	<p>Pemerintah Kabupaten Wonosobo membuktikan komitmennya&nbsp;dalam mewujudkan&nbsp;keterbukaan informasi publik. Yang ditandai dengan apresiasi dari Komisi Informasi Publik Provinsi Jawa Tengah,&nbsp;bahwa penyelenggaraan pemerintahan Kabupaten Wonosobo dari menuju informatif menjadi informatif. Hal ini, tentu&nbsp;menjadi parameter awal&nbsp;dalam&nbsp;merancang strategi&nbsp;untuk&nbsp;mempertahankan&nbsp;dan meningkatkan atas capaian yang sudah diraih. Sebagaimana disampaikan Kepala Dinas Komunikasi dan Informatika Kabupaten Wonosobo Fahmi Hidayat dalam arahannya saat Rapat Koordinasi PPID Pelaksana Kabupaten Wonosobo Tahun 2023, di Ruang Rapat Utama Diskominfo, Rabu, (18\/01\/2023).</p>
	<p>Lebih lanjut Fahmi menyampaikan, dampak dari level informatif sangatlah&nbsp;besar bagi dunia usaha, investor, dan lembaga pers. Untuk itu,&nbsp;PPID Pelaksana Wonosobo diminta&nbsp;memaksimalkan kualitasnya pada&nbsp;pengelolaan&nbsp;website dan media sosial,&nbsp;mengingat keterbukaan merupakan salah satu mandat reformasi 1999&nbsp;yang harus bisa direalisasikan.</p>
	<p>Menurut&nbsp;Fahmi, teknologi digital&nbsp;akan berdampak&nbsp;efektif&nbsp;ketika menerapkan&nbsp;strategi komunikasi yang baik, begitu juga sebaliknya. Maka&nbsp;dalam melaksanakan aktivitas&nbsp;di pemerintahan, kita&nbsp;dituntut&nbsp;lebih informatif melalui pemanfaatan teknologi digitalisasi&nbsp;yang ada saat&nbsp;ini.</p>
	<p>&ldquo;Strategi komunikasi digital kita harus lebih optimal lagi, bagaimana memudahkan seluruh masyarakat dalam mengakses layanan sosial dan layanan publik lainnya,&nbsp;mari bersama kita desain inovasi publik berbasis digital&nbsp;dengan&nbsp;lebih baik,&nbsp;kurang lebih 13 bulan ke depan menuju Pemilu 2024, PPID Pelaksana diminta menyikapi secara bijak karena tingginya tensi pemilu yang akan dihadapi,&rdquo;&nbsp;pinta Fahmi.</p>
	<p>Kepala Bidang Informatika Diskominfo Wonosobo Sugeng Riyadi menambahkan, capaian SPBE Pemkab Wonosobo di tahun 2022 masuk kategori baik meskipun capaian indeks angkanya masuk kategori sedang, karena terdapat indikator penilaian tambahan yang belum bisa dipenuhi sehingga mengurangi bobot penilaian.</p>
	<p>&ldquo;Tahun 2023 ini Diskominfo akan membenahi tata kelola data di Perangkat Daerah sebelum dipublikasikan lewat Satu Data, untuk itu dibutuhkan keterlibatan semua sumber daya yang mumpuni dan memahami betul ketersediaan keseluruhan data di PPID Pelaksana,&rdquo; pungkas Sugeng.</p>
	<p>Sementara itu, Kepala Bidang Informasi Komunikasi Publik Diskominfo Wonosobo Aldhiana Kusumawati S.STP menambahkan, pihaknya selama kurang lebih 2 bulan ke depan akan fokus membenahi perbaikan layanan informasi, penyusunan daftar informasi publik, perbaikan kelembagaan PPID Pembantu, dan pemutakhiran informasi berkala di media sosial.</p>
</div>